### ISSUE TITLE
Add project description to README.md file

### ISSUE THREAD

**Issue by AndrewSmrnv** [VSemenovykh/AutoAdsApp#1]
Add project description to README.md file.
Project goals/functions.

**Comment by VSemenovykh** [comment]
added project description to README.md file and goals/functions

**Comment by AndrewSmrnv** [comment]
Please change upload to update in the "CRUD: create, read, upload and delete"

**Comment by AndrewSmrnv** [comment]
Reorganize list of project functions depends on the priority
