### ISSUE TITLE
Create data model UML diagram

### ISSUE THREAD

**Issue by AndrewSmrnv** [VSemenovykh/AutoAdsApp#2]
Create a data model UML diagram for the project. 
Show all data model classes and dependencies between them.

**Comment by VSemenovykh** [comment]
![screenshot-diagram](https://user-images.githubusercontent.com/71659506/108228392-df70d180-714f-11eb-9553-3fc005151973.JPG)

**Comment by VSemenovykh** [comment]
added a screenshot data model UML diagram for the project.

**Comment by VSemenovykh** [comment]
added comment data model to README.md
